sudo: required
services:
  - docker

before_install:
  - docker build -t adiilak/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adiilak/react-test npm test

after_success:
  - docker build -t adilak0096/multi-client ./client
  - docker build -t adilak0096/multi-nginx ./nginx
  - docker build -t adilak0096/multi-server ./server
  - docker build -t adilak0096/multi-worker ./worker
# Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push adilak0096/multi-client
  - docker push adilak0096/multi-nginx
  - docker push adilak0096/multi-server
  - docker push adilak0096/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: elasticbeanstalk-ap-southeast-1-316539549228
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY